[default]
extend-ignore-re = [
  ".*// typos:disable-line[^\\n]*\\n[^\\n]*\\n",
]

[default.extend-words]
shure = "shure" # Brandname
Automattic = "Automattic" # Brand name in license.md
helo = "helo" # AJA-Helo
livetime = "livetime" # workflownetwork-livetime

[default.extend-identifiers]
sACN = "sACN"
PNGs = "PNGs"

[files]
extend-exclude = [
  "**/*.companionconfig",
]
